# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78e6b062ec02132a8708b92fac40043b2c3e764197f0ae137071498c569226aa86c57915c26fc2552f78f259cb35c002695f72fdd589123cf0fe8d75ae6a0a8e

test:
  secret_key_base: 0e328ae3ef1620e1021a9396e10d3db6ecedc6726f8b642b820e47d6ecb9a4ef7270ff9edf6c4db6e99310dd582237b44d68ebf7e15130160c9a7cb878ae9643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
